name: geolocator_web
description: Official web implementation of the geolocator plugin.
homepage: https://github.com/Baseflow/flutter-geolocator/tree/geolocator_web
version: 2.0.3
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GeolocatorPlugin
        fileName: geolocator_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  geolocator_platform_interface: #^2.0.0
     path: ../geolocator_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0"
